[LAB-5] Added push-notifications + PWA
puhlenkiyroman/effective_course pull request #5
Opened 2024-05-15 12:00 UTC by puhlenkiyroman

Litvinenko Roman

2024-05-22 06:25 UTC, konstantinzelinsky requested changes
Надо перенести логику из js скрипта в React.
В остальном всё хорошо

2024-05-22 06:25 UTC, konstantinzelinsky commented on package.json
> +    "express": "^4.19.2",
Не стоит добавлять в зависимости фронтенд приложения зависимости от бэка. Нужно либо вынести в отдельный репозиторий, либо, если у тебя бэк полностью совпадает с тем, который в примере, то не надо его код добавлять в репозиторий

2024-05-22 06:25 UTC, konstantinzelinsky commented on public/index.js
> +const publicKey = 'BJXtHJEgXMd9P2p-X-HxbF4t7-xJnqy6EuyXeM1YN39911MlqG_UMnHJYaI695VG0FarpabdAIocgHBw-m_OYWs';
Логика из этого файла должна быть в React приложении, это не должен быть отдельный js файл

2024-05-22 06:51 UTC, konstantinzelinsky commented on package.json
> +    "express": "^4.19.2",
В рамках данной работы уже необязательно выносить или убирать код бэк. Можно оставить

2024-05-22 06:52 UTC, konstantinzelinsky commented on package.json
> +    "express": "^4.19.2",
В рамках данной работы уже необязательно выносить или убирать код бэка. Можно оставить

2024-05-28 11:10 UTC, konstantinzelinsky commented
Ожидаю исправления работы

2024-05-28 11:13 UTC, puhlenkiyroman commented
@konstantinzelinsky привет, помню, завтра исправлю

2024-05-29 08:54 UTC, puhlenkiyroman commented
@konstantinzelinsky переделал

2024-06-03 04:59 UTC, konstantinzelinsky approved these changes
Принял
7 + 2

2024-06-03 04:59 UTC, konstantinzelinsky commented on src/index.tsx
> +        <div id="message">
Отрисовывать сообщение таким образом в работе не требовалось. Логика с пушами ничего не должна рендерить. Поэтому было бы правильнее сделать ее не компонентом, а кастомным хуком, и вызывать его там, где это требуется

2024-06-06 09:02 UTC, merged